### ISSUE TITLE
`LogEvent`s and statuses

### ISSUE THREAD

**Issue by lemontree210** [samanthasgroup/django-webapps#107]
## Types of events by their origin
1. Events triggered by **coordinators**. These events can be triggered:
    - explicitly. When something happens with a student or a teacher (e.g. they want to end their participation in the project or go on leave), the coordinator *explicitly* triggers a corresponding event (e.g. by selecting it from a list and pressing "Submit" or by pressing one of the array of event-related buttons). 
    - implicitly. A coordinator performs and action *without explicitly pressing a button whose sole purpose is to create a `LogEvent`*. But this action triggers this event nevertheless. One example is transferring a student to another group. I think that in this case the dashboard will be "unaware" of the event mechanics and just send a request "transfer the student from here to there", and the backend will know that this must also trigger an event.
2. Same for **admins** that perform actions on coordinators. However, it is yet unclear where we're going to implement this: in a separate ToolJet dashboard or in Django admin.
3. Events triggered by the **bot** (e.g. user replied that they no longer want to study/teach at all)
4. Timed events triggered **automatically by the backend itself**:
  - "cron" events (e.g. once a day the backend tries to build groups and triggers corresponding events in case of success)
  - "timeout" events (e.g. the user has been inactive for 3 weeks)

**TODO Include exhaustive lists of events of all types in a separate sections**

## Workflow

When an event is triggered, the following happens: 

- a POST request is sent to the backend (for all items except 4 and possibly 2)
- in the backend:
    - a `LogEvent' object is created
    - a new status is assigned according to the rules, maybe outlined in a YAML file
    - `status_since` is set to current time
    - the response includes the new `status`, `status_since` and serialized `LogEvent`.
- the client performs its action (dashboard shows updated information: new `status` and `status_since`, the profile shows the new even; bot says something to the user etc.)

**Comment by lemontree210** [comment]
Just a crude first idea of what the configuration might look like:

```yaml
---
# Keys are internal names of events that are not stored in the database.
# They affect the code, so they could even be put into a Python module.
# It just seems logical to store them in a YAML (or similar) format so as not to clutter code.
bot:  # events triggered by bot
  registered:  # name of abstract event
    student:  # resulting actions for student
      log_event: registered
      status: awaiting_offer
    teacher:
      log_event: registered
      status: awaiting_offer
    teacher_under_18:
      log_event: registered
      status: active
    # action_for_coordinator when we add coordinator-related functionality to bot
human:  # events triggered from ToolJet or Django admin site
  requested_transfer:
    student:
      log_event: requested_transfer
      status: needs_transfer
    teacher:
      log_event: requested_transfer
      status: needs_transfer
    coordinator:
      log_event: requested_transfer
      status: needs_transfer
  missed_class_silently:
    student:
      log_event: missed_class_silently
timed:  # events triggered by duration of something
  onboarding_stale:
    coordinator: # this event is for coordinator only. Coordinator didn't take a group after onboarding
      timeout: 1w
      status: onboarding_stale
numbered:  # events triggered by number of times something happened
    student:
      - event: missed_class_silently  # event that has to be counted
        repeats: 3
        status: not_attending
...

```
